#ifndef XMLSCRIPT_H
#define XMLSCRIPT_H

extern const char SampleConfig[] =
	"<OpenNI>\n"
	"\t<Licenses>\n"
	"\t\t<!-- Add application-specific licenses here \n"
	"\t\t<License vendor=\"vendor\" key=\"key\"/>\n"
	"\t\t-->\n"
	"\t</Licenses>\n"
	"\t<Log writeToConsole=\"false\" writeToFile=\"false\">\n"
	"\t\t<!-- 0 - Verbose, 1 - Info, 2 - Warning, 3 - Error (default) -->\n"
	"\t\t<LogLevel value=\"3\"/>\n"
	"\t\t<Masks>\n"
	"\t\t\t<Mask name=\"ALL\" on=\"true\"/>\n"
	"\t\t</Masks>\n"
	"\t\t<Dumps>\n"
	"\t\t</Dumps>\n"
	"\t</Log>\n"
	"\t<ProductionNodes>\n"
	"\t\t<!-- Uncomment following line, in order to run from a recording \n"
	"\t\t<Recording file=\"sampleRec.oni\" />\n"
	"\t\t-->\n"
	"\t\n"
	"\t\t<!-- Set global mirror -->\n"
	"\t\t<GlobalMirror on=\"true\"/>\n"
	"\t\t\n"
	"\t\t<!-- Create a depth node and give it a name alias (useful if referenced ahead in this script) -->\n"
	"\t\t<Node type=\"Depth\" name=\"MyDepth\">\n"
	"\t\t\t<Query>\n"
	"\t\t\t\t<!-- Uncomment to filter by vendor name, product name, etc.\n"
	"\t\t\t\t<Vendor>MyVendor inc.</Vendor>\n"
	"\t\t\t\t<Name>MyProduct</Name>\n"
	"\t\t\t\t<MinVersion>1.2.3.4</MinVersion>\n"
	"\t\t\t\t<Capabilities>\n"
	"\t\t\t\t\t<Capability>Cropping</Capability>\n"
	"\t\t\t\t</Capabilities>\n"
	"\t\t\t\t-->\n"
	"\t\t\t</Query>\n"
	"\t\t\t<Configuration>\n"
	"\t\t\t\t<!-- Uncomment to set requested mode\n"
	"\t\t\t\t<MapOutputMode xRes=\"640\" yRes=\"480\" FPS=\"30\"/> \n"
	"\t\t\t\t-->\n"
	"\n"
	"\t\t\t\t<!-- Uncomment to override global mirror\n"
	"\t\t\t\t<Mirror on=\"false\" /> \n"
	"\t\t\t\t-->\n"
	"\t\t\t</Configuration>\n"
	"\t\t</Node>\n"
	"\t\t\n"
	"\t\t<!-- Create an image node. If it fails, continue anyway. -->\n"
	"\t\t<Node type=\"Image\" stopOnError=\"false\" />\n"
	"\n"
	"\t\t<!-- Uncomment nodes from here if you need them.\n"
	"\t\t<Node type=\"Audio\" />\n"
	"\t\t<Node type=\"User\" />\n"
	"\t\t<Node type=\"Hands\" />\n"
	"\t\t<Node type=\"Gesture\" />\n"
	"\t\t<Node type=\"Scene\" />\n"
	"\t\t-->\n"
	"\t</ProductionNodes>\n"
	"</OpenNI>\n";

#endif // XMLSCRIPT_H
